# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Semaloop < Formula
  desc "Command-line interface for Semaloop"
  homepage "https://semaloop.com"
  version "1.0.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/semaloop/cli/releases/download/v1.0.0/cli_Darwin_x86_64.tar.gz"
      sha256 "f8edcc6d353e9781d582abb18b1e7bc31d247431facf2ed318aa59287b384bcc"

      def install
        bin.install "semaloop"
      end
    end
    on_arm do
      url "https://github.com/semaloop/cli/releases/download/v1.0.0/cli_Darwin_arm64.tar.gz"
      sha256 "9bdd9a5e107f81c3efe6cfae4a044a6ef79e4b6701be54715f1545d315cfecbe"

      def install
        bin.install "semaloop"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/semaloop/cli/releases/download/v1.0.0/cli_Linux_x86_64.tar.gz"
        sha256 "6bd694edeabc297778fef7776b15ec6cfde5fd55db8e38c40ca113d8189fdcd8"

        def install
          bin.install "semaloop"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/semaloop/cli/releases/download/v1.0.0/cli_Linux_arm64.tar.gz"
        sha256 "6775bfd85bd433f2768f745cc9b64373ee690bab4e1a78176db482a07570ebae"

        def install
          bin.install "semaloop"
        end
      end
    end
  end

  test do
    system "#{bin}/semaloop", "--version"
  end
end
